---
- name: Restart Vault Agent
  listen: "Restart Vault Agent"
  ansible.builtin.systemd:
    name: vault-agent
    state: restarted

- name: Restart Route Service
  listen: "Restart Route Service"
  ansible.builtin.systemd:
    name: fix-vault-routes.service
    state: restarted
    daemon_reload: true
