---
vault_target_os: "linux"
vault_target_arch: "amd64"
vault_target_version: "1.21.1"

# Load Balancer
haproxy_frontend_port: 443
haproxy_stats_port: 8404
haproxy_stats_user: "admin"

# System Identity
vault_owner: vault
vault_group: vault

# Standard Directory Structure
vault_dir_config: "/etc/vault.d"
vault_dir_tls: "/etc/vault.d/tls"
vault_dir_data: "/opt/vault/data"

# Network Defaults
vault_port_api: 8200
vault_port_cluster: 8201

# PKI Defaults
vault_ca_subject_common_name: "Vault Root CA"
vault_cluster_name: "vault-ha-cluster"

# Development Vault Path for 'community.hashi_vault.vault_kv2_get'
dev_vault_api_path: "on-premise-gitlab-deployment/infrastructure"
dev_vault_url: "https://127.0.0.1:8200"
dev_root_token_path: "{{ playbook_dir }}/../../vault/keys/root-token.txt"
