---
- name: "Step 1. Install Docker SDK for Python"
  ansible.builtin.pip:
    name: "{{ docker_base.packages.pip }}"
    state: present
    extra_args: "--break-system-packages"

- name: "Step 2. Create directory for Docker GPG key"
  ansible.builtin.file:
    path: "{{ docker_base.os_config.ubuntu.gpg_keyring_dir }}"
    state: directory
    mode: "0755"

- name: "Step 3. Add Docker's official GPG key"
  ansible.builtin.get_url:
    url: "{{ _docker_base_gpg_url }}"
    dest: "{{ _docker_base_gpg_path }}"
    mode: "a+r"

- name: "Step 4. Add Docker's APT repository"
  ansible.builtin.apt_repository:
    repo: "{{ _docker_base_repo_string }}"
    state: present

- name: "Step 5. Install Docker Engine and related packages"
  ansible.builtin.apt:
    name: "{{ docker_base.packages.apt }}"
    state: present
    update_cache: true

- name: "Step 6. Add user to the 'docker' group"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ docker_base.group_name }}"
    append: true

- name: "Step 7. Verify Docker installation"
  ansible.builtin.command:
    cmd: "docker info"
  become: true
  changed_when: false
