---
etcd_base:
  version: "v3.5.14"
  binary:
    url_base: "https://github.com/etcd-io/etcd/releases/download"
    install_path: "/usr/local/bin"
    files:
      - etcd
      - etcdctl

# Internal variables for download logic
_etcd_base_archive_name: "etcd-{{ etcd_base.version }}-linux-amd64.tar.gz"
_etcd_base_download_url: "{{ etcd_base.binary.url_base }}/{{ etcd_base.version }}/{{ _etcd_base_archive_name }}"
_etcd_base_temp_path: "/tmp/{{ _etcd_base_archive_name }}"
_etcd_base_temp_extract_path: "/tmp/etcd-{{ etcd_base.version }}-linux-amd64"
