---
- name: "Play 1: Configure MinIO High Availability Cluster"
  hosts: minio_nodes
  become: true
  roles:
    - 36-minio-distributed

- name: "Play 2: Configure HAProxy for Load Balancing"
  hosts: haproxy_nodes
  become: true
  roles:
    # - 37-minio-ha-loadbalancer
