---
# (HA) ETCD
- name: "Play [ETCD]: Configure etcd Cluster"
  hosts: postgres_etcd_nodes
  become: true
  roles:
    - 22-postgres-etcd

# Patroni
- name: "Play [Postgres]: Configure Patroni and PostgreSQL Cluster"
  hosts: postgres_db_nodes
  become: true
  roles:
    - 23-postgres-patroni

# Redis Sentinel
- name: "Play [Redis]: Configure Redis High Availability Cluster"
  hosts: redis_db_master, redis_db_replicas
  become: true
  roles:
    - 26-redis-sentinel

# MinIO Distributed
- name: "Play [MinIO]: Configure MinIO High Availability Cluster"
  hosts: minio_db_nodes
  become: true
  roles:
    - 28-minio-distributed

# Dev Harbor Bootstrapper Registry
- name: "Play [Dev Harbor]: Configure Dev Harbor (Bootstrapper) Cluster"
  hosts: dev_harbor_nodes
  become: true
  roles:
    - 29-dev-harbor-registry
