---
- name: Section D. Install Kubernetes components
  block:
    - name: "Step 1a. Download Kubernetes GPG key"
      ansible.builtin.get_url:
        url: "{{ _kubeadm_base_repo_k8s_gpg_url }}"
        dest: "{{ _kubeadm_base_repo_k8s_data.gpg_key_temp_path }}"
        mode: "0644"

    - name: "Step 1b. Dearmor Kubernetes GPG key"
      ansible.builtin.command:
        cmd: "gpg --dearmor -o {{ _kubeadm_base_repo_k8s_data.gpg_keyring_path }} {{ _kubeadm_base_repo_k8s_data.gpg_key_temp_path }}"
      args:
        creates: "{{ _kubeadm_base_repo_k8s_data.gpg_keyring_path }}"
      register: gpg_dearmor_k8s_result
      changed_when: gpg_dearmor_k8s_result.rc == 0 and 'overwrite' not in gpg_dearmor_k8s_result.stderr

    - name: "Step 2. Add Kubernetes apt repository"
      ansible.builtin.apt_repository:
        repo: "{{ _kubeadm_base_repo_k8s_string }}"
        state: present
        filename: "{{ _kubeadm_base_repo_k8s_data.filename }}"
        update_cache: true

    - name: "Step 3. Install kubeadm, kubelet, kubectl"
      ansible.builtin.apt:
        name: "{{ _kubeadm_base_k8s_versioned_packages }}"
        state: present

    - name: "Step 4. Hold Kubernetes package versions"
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: "{{ kubeadm_base.packages.apt.kubernetes }}"

    - name: "Step 5. Enable the kubelet service"
      ansible.builtin.systemd:
        name: kubelet
        enabled: true

    - name: "Step 6. Clean up temporary files"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ _kubeadm_base_repo_crio_data.gpg_key_temp_path }}"
        - "{{ _kubeadm_base_repo_k8s_data.gpg_key_temp_path }}"

    # - name: "Step 6. Pre-pull container images for control plane"
    #   ansible.builtin.command: kubeadm config images pull --cri-socket unix:///var/run/crio/crio.sock
    #   changed_when: true
